version: 2
jobs:
  build:
    working_directory: ~/ng2-simple-loading
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test
      - store_artifacts:
          path: test-results.xml
          prefix: tests