version: 2
jobs:
  build:
    working_directory: ~/ng2-simple-loading
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.lock" }}
      - run:
          name: install gulp
          command: npm install gulp -g
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.lock" }}
          paths:
            - ./node_modules
      - run:
          name: angular-build
          command: gulp
      - run:
          name: angular-test
          command: gulp test
      - store_artifacts:
          path: test-results.xml
          prefix: tests